update feedparser to ^6.0
Python 3.9 is out and `base64.decodestring` used in old version of feedparser is removed.

```
>>> from pelican.plugins import webring                                                                                                     
Traceback (most recent call last):                                                                                                          
  File "<stdin>", line 1, in <module>                                                                                                       
  File "/home/nicolas/Sources/git.sr.ht/~nka/blog/.venv/lib/python3.9/site-packages/pelican/plugins/webring/__init__.py", line 1, in <module
>                                                                                                                                           
    from .webring import *  # NOQA                                                                                                          
  File "/home/nicolas/Sources/git.sr.ht/~nka/blog/.venv/lib/python3.9/site-packages/pelican/plugins/webring/webring.py", line 17, in <module
>                                                                                                                                           
    import feedparser                                                                                                                       
  File "/home/nicolas/Sources/git.sr.ht/~nka/blog/.venv/lib/python3.9/site-packages/feedparser.py", line 93, in <module>
    _base64decode = getattr(base64, 'decodebytes', base64.decodestring)
AttributeError: module 'base64' has no attribute 'decodestring'
```

Version 6.0 has the required fix: https://github.com/kurtmckee/feedparser/pull/206